# WINDOWS
WINDOW_WIDTH = 1650
WINDOW_HEIGHT = 800
WINDOW_FONT = 'Courier'

HEIGHT = 595
MARGIN_X = 0
MARGIN_Y = 0
TEXT_MARGIN_X = 6
TEXT_MARGIN_Y = 10
CHAR_HEIGHT = 18
NB_COLUMNS = 16
NB_ROWS = 20
HEADER_HEIGHT = CHAR_HEIGHT

YAML_FILE_FORMAT_PATH = 'D:/Python/Projets/!!/__data__/yaml/File_Format_Structure/'

COLOR_GRAPH_BACKGROUND = '#cccccc'

COLOR_HIGHLIGHT = 'yellow'
COLOR_SELECTED = 'white'

# LINE_COLOR_OFFSET = COLOR_GRAPH_BACKGROUND
# LINE_COLOR_HEX = COLOR_GRAPH_BACKGROUND
# LINE_COLOR_ASCII = COLOR_GRAPH_BACKGROUND
LINE_COLOR_OFFSET = 'black'
LINE_COLOR_HEX = 'black'
LINE_COLOR_ASCII = 'black'

FILL_COLOR_OFFSET = 'white'
FILL_COLOR_HEX = 'white'
FILL_COLOR_ASCII = 'white'

FILL_COLOR_SELECTED_HEX = 'blue'
FILL_COLOR_SELECTED_ASCII = 'blue'

FILL_COLOR_HIGHLIGHT_HEX = 'yellow'
FILL_COLOR_HIGHLIHT_ASCII = 'yellow'

# CELL_COLOR_NORMAL_HEX = 'gray'
# CELL_COLOR_NORMAL_ASCII = 'gray'

# TREE
TREE_NB_ROWS = 1
TREE_FIRST_WIDTH = 30
TREE_DEFAULT_WIDTH = 10
TREE_FONT = 'Courier 10'

# GRAPH
GRAPH_WIDTH = 700
GRAPH_HEIGHT = 800

# OFFSET
OFFSET_WIDTH = 70
OFFSET_HEIGHT = HEIGHT
OFFSET_MARGIN_X = MARGIN_X
OFFSET_MARGIN_Y = MARGIN_Y + HEADER_HEIGHT
OFFSET_CELL_WIDTH = 70
OFFSET_CELL_HEIGHT = CHAR_HEIGHT


# HEX
HEX_WIDTH = 345
HEX_HEIGHT = HEIGHT
HEX_MARGIN_X = MARGIN_X + OFFSET_WIDTH + 10
HEX_MARGIN_Y = MARGIN_Y + HEADER_HEIGHT
HEX_CHAR_WIDTH = 8 # Width of a character
HEX_CHAR_HEIGHT = CHAR_HEIGHT # Height of a character
HEX_SPACING_X = 4 # Width between two values
HEX_SPACING_Y = 0 # Height between two values
HEX_CELL_WIDTH = 2 * HEX_CHAR_WIDTH + HEX_SPACING_X
HEX_CELL_HEIGHT = HEX_CHAR_HEIGHT

HEX_BOX_MARGIN_X = 4 + OFFSET_WIDTH # Adjusting the margin for Box in the HEX Graph
HEX_BOX_MARGIN_Y = 4 # Adjusting the margin for Box in the HEX Graph

# DEC
ASCII_WIDTH = 200
ASCII_HEIGHT = HEIGHT
ASCII_MARGIN_X = MARGIN_X + HEX_WIDTH + OFFSET_WIDTH
ASCII_MARGIN_Y = MARGIN_Y + HEADER_HEIGHT
ASCII_CHAR_WIDTH = 8 # Width of a character
ASCII_CHAR_HEIGHT = CHAR_HEIGHT # Height of a character
ASCII_SPACING_X = 2 # Width between two values
ASCII_SPACING_Y = 2 # Height between two values
ASCII_CELL_WIDTH = ASCII_CHAR_WIDTH + ASCII_SPACING_X
ASCII_CELL_HEIGHT = ASCII_CHAR_HEIGHT


# COLUMN
COLUMN_WIDTH = OFFSET_WIDTH + HEX_WIDTH + ASCII_WIDTH
COLUMN_HEIGHT = HEIGHT + 10
COLUMN_BACKGROUND_COLOR = '#CCCCCC'

JUMP_X = 12 # Adjusting for the margin
JUMP_Y = 13 # Adjusting for the margin
JUMP_ADRESS_X = 20 # Adjusting for margin in adress
CHAR_X = 8 # Width of a character
CHAR_Y = 18 # Height of a character
# SPACE_X = 2 # Width between two character
# SPACE_Y = 2 # Height between two character
# SKIP_AFTER = 4 # Make a space on hex view after each _ character
# SKIP_X = 0 # Width to skip at each SKIP_AFTER